use_frameworks!

platform :ios, '9.0'

target 'TransakSwift_Example' do
  pod 'TransakSwift', :path => '../'

  target 'TransakSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
