use_frameworks!

platform :ios, '12.0'

target 'TransakSwift_Example' do
  pod 'TransakSwift', :path => '../'
  pod 'BEPureLayout', :git => 'https://github.com/bigearsenal/BEPureLayout.git'

  target 'TransakSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
